# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa3746934d213dd8a77b6dc230fc1ac398c6a33594a65b90ab56e5ae65fe06a935c71011451156dd39b27a312aa6da29a428ffd9029cc14f65cae6a090155de0

test:
  secret_key_base: 2b13485b082ea86024de08a098c70b3b9af346b7f90419433f626ae46262fe6865b4c5f0805bf4d5386389a9ad79cbf4deb814850080a8667bbad66eb65c8ae2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
